import { chromium } from '/Users/joe/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.mjs'
const browser=await chromium.launch({headless:true,executablePath:'/Users/joe/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'})
try {
  const page=await browser.newPage({viewport:{width:1500,height:1000}})
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto(process.env.BLOX_PREVIEW_URL??'http://127.0.0.1:5178')
  await page.getByRole('button',{name:'Create Project',exact:true}).waitFor()
  await page.evaluate(async()=>{
    const {useStore}=await import('/src/store/useStore.ts')
    const s=useStore.getState();s.createProject('Willow House · Drawing structure','quarter')
    const add=(id,x,y,w,h)=>{s.placeElement(id,x,y,w,h);return useStore.getState().project.elements.at(-1).id}
    s.updateLayer(s.activeLayerId,{name:'Architecture'})
    for(const [x,y,w,h] of [[0,0,28,.5],[0,20,28,.5],[0,0,.5,20],[27.5,0,.5,20]]) add('wall-exterior',x,y,w,h)
    s.addLayer('Furniture')
    const sofa=add('furniture-sofa',4,5,7,2.833),table=add('furniture-coffee-table',5,10,4,2)
    s.selectMany([sofa,table]);s.groupSelected();s.renameGroup(useStore.getState().project.groups[0].id,'Lounge')
    add('furniture-desk',19,5,5,2.5)
    s.addLayer('Annotations')
    const note=add('annotation-leader',8,14,7,2)
    s.updateElement(note,{properties:{label:'Verify clear opening',fontSize:12}})
    s.clearSelection()
  })
  const frame=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))
  await frame();await page.evaluate(async()=>{const {useStore}=await import('/src/store/useStore.ts');useStore.getState().setStageTransform(100,90,1)})
  await page.getByRole('button',{name:'Layers',exact:true}).click()
  await page.getByRole('button',{name:'Activate layer Furniture',exact:true}).focus();await page.keyboard.press('Enter')
  await page.getByRole('button',{name:'Hide layer Furniture',exact:true}).click()
  await page.getByRole('button',{name:'Show layer Furniture',exact:true}).click()
  await page.getByRole('button',{name:'Lock layer Furniture',exact:true}).click()
  await page.getByRole('button',{name:'Unlock layer Furniture',exact:true}).click()
  await page.getByRole('button',{name:'Rename layer Furniture',exact:true}).click()
  await page.getByLabel('Layer name',{exact:true}).fill('Discard me');await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Activate layer Furniture',exact:true}).waitFor()
  await page.getByRole('button',{name:'Rename layer Furniture',exact:true}).click()
  await page.getByLabel('Layer name',{exact:true}).fill('Interiors');await page.keyboard.press('Enter')
  await page.getByRole('button',{name:'Collapse group Lounge',exact:true}).click()
  await page.getByRole('button',{name:'Expand group Lounge',exact:true}).click()
  await page.getByRole('button',{name:'Edit group Lounge',exact:true}).click()
  await page.getByRole('button',{name:'Finish editing group',exact:true}).waitFor()
  await frame();await page.screenshot({path:'artifacts/layers-groups.png'})
  await page.getByRole('button',{name:'Finish editing group',exact:true}).click()
  await page.getByRole('button',{name:'Rename group Lounge',exact:true}).click()
  await page.getByLabel('Group name',{exact:true}).fill('Discard group');await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'Select group Lounge',exact:true}).waitFor()
  await page.getByRole('button',{name:'Add layer',exact:true}).click()
  const temp=await page.evaluate(async()=>{const {useStore}=await import('/src/store/useStore.ts');return useStore.getState().project.layers.at(-1).name})
  await page.getByRole('button',{name:`Delete layer ${temp}; move objects to Default`,exact:true}).click()
  await page.getByRole('button',{name:'Activate layer Interiors',exact:true}).click()
  await frame();await page.screenshot({path:'artifacts/layers-panel.png'})
  await page.evaluate(async()=>{const {useStore}=await import('/src/store/useStore.ts');const s=useStore.getState();s.selectMany([s.project.elements.find(e=>e.bloxId==='annotation-leader').id])})
  const inspector=page.getByRole('region',{name:'Selection properties'})
  await inspector.getByRole('textbox').fill('Confirm opening on site')
  await frame();await page.screenshot({path:'artifacts/inspector-annotation.png'})
  await page.setViewportSize({width:1000,height:850});await frame();await page.screenshot({path:'artifacts/layers-compact.png'})
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Compact layout overflow')
  const result=await page.evaluate(async()=>{
    const {useStore}=await import('/src/store/useStore.ts');const s=useStore.getState()
    const layer=s.project.layers.find(l=>l.name==='Interiors')
    if(!layer?.visible||layer.locked||s.activeLayerId!==layer.id||s.activeGroupId) throw new Error('Layer state mismatch')
    if(s.project.elements.find(e=>e.bloxId==='annotation-leader').properties.label!=='Confirm opening on site') throw new Error('Annotation edit failed')
    return {layers:s.project.layers.length,objects:s.project.elements.length}
  })
  if(errors.length) throw new Error(errors.join('\n'))
  console.log(JSON.stringify({...result,errors}))
} finally {await browser.close()}
